<style type="text/css">
    .instructions {
        text-align: justify;
        margin: 5px;
        padding-left: 20px;
    }
    
    .instructions li {
        padding: 5px 0;
    }
</style>

<form>
    <fieldset>
        <legend>Komunikacja</legend>
        <ol class="instructions">
            <li>Lewy panel służy do generowania zestawów – po wybraniu podręcznika określ typ testu (kierunek tłumaczenia), zakres materiału (rozdziały) oraz poziom trudności. Kolokwium semestralne zawiera losowy test mieszany.</li>
            <li>Prawy panel umożliwia sprawdzenie słówek <b>wyłącznie</b> w znaczeniu użytym w danym rozdziale.</li>
            
            <li>Spróbuj ustnie przetłumaczyć wylosowany zestaw. Jeśli nie znasz znaczenia lub nie masz pewności, skorzystaj ze słownika.</li>
            <li>Możesz wydrukować słownictwo w języku angielskim - po wybraniu tłumaczenia <i>z angielskiego na polski</i> i zaznaczeniu interesujących Cię rozdziałów, użyj <i>Pobierz PDF</i>.</li>
            <a style="float: right;font-size: 13pt;color: rgb(56, 162, 250);text-decoration: none;" href="?more-details">Więcej</a>
        </ol>
    </fieldset>
</form>