<style type="text/css">
    .test {
        width: 500px;
    }
    
    .dictionary {
        width: 430px;
    }
    
    .dictionary td {
        padding: 0;
    }
    
    .dictionary .gadget {
        height: 165px;
    }
    
    .documents {
        padding: 10px 25px;
    }
</style>

<div class="clear">
    <div class="test left">
        <?= $this->form; ?>
    </div>
    <div class="dictionary right">
        <form action="http://www.1a.biz.pl/slownik/szukajskr.php" method="post" encType="multipart/form-data" target="dictionary">
            <fieldset>
                <legend><?= $this->translate('dictionary'); ?></legend>
                <script src="//www.gmodules.com/ig/ifr?url=http://www.deptmit.webs.com/GoogleTranslateGadget2.xml&amp;up_sl=en&amp;up_tl=pl&amp;up_default_text=&amp;synd=open&amp;w=360&amp;h=165&amp;title=Tłumacz+Google&amp;lang=pl&amp;country=ALL&amp;border=http%3A%2F%2Fwww.gmodules.com%2Fig%2Fimages%2F&amp;output=js"></script>
                <!--<table width="270" bgcolor="#E1E1E1" >
                    <tr>
                        <td>
                            <font face="Arial" size="2">
                                <a href="http://www.1a.biz.pl/slownik" style="font-family: Arial; text-decoration: none;  font-size: 12px;  font-weight: bold;  font-style: normal;  color: black">
                                    <b>Angielski słownik naukowo-techniczny </b>
                                </a>
                            </font>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <font face="Arial" size="1"><b><input type="text" name="slowo" size="12" value=""></b></font>
                            <img border="0" src="http://www.1a.biz.pl/flags/anglia.gif" width="17" height="11" alt="English" />
                            <input type="radio" name="jezyk" value="ang>pol" />
                            <img border="0" src="http://www.1a.biz.pl/flags/polska.gif" width="17" height="11" alt="Polski" />
                            <input type="radio" name="jezyk" value="pol>ang" />
                            <input type="submit" value="szukaj" style="font-family: Arial; font-size: 9pt; font-weight: bold" />
                        </td>
                    </tr>
                </table>
                <iframe name="dictionary" style="border: none; width: 100%; height: 512px;"></iframe>-->
            </fieldset>
        </form>
        <?= $this->render('home/parts/instructions.phtml'); ?>
    </div>
</div>