<style type="text/css">
    .instructions {
        text-align: justify;
        margin: 5px;
        padding-left: 20px;
    }
    
    .instructions li {
        padding: 5px 0;
    }
</style>

<form>
    <fieldset>
        <legend>Instrukcje</legend>
        <ol class="instructions">
            <li>Uczenie się słówek wymaga systematyczności - każdy sprawdzian notuj w swoim SÓWKOBLOGU (data, rozdział, słowka, wynik).</li>
            <li>Po wylosowaniu przepisz zestaw.</li>
            <li>Na sprawdzian masz pięć minut.</li>
            <li>Jeśli nie znasz znaczenia, podkreśl wyraz; jeśli masz wątpliwości, postaw przy swoim tłumaczeniu znak zapytania.</li>
            <li>Sprawdź w słowniku wyrazy z pytajnikami i podlicz swój wynik.</li>
            <li>Następnie sprawdź słówka podkreślone.</li>
            <li>Nie zapomnij zrobić notatki ze słownictwa, które sprawiło Ci kłopoty.</li>
        </ol>
    </fieldset>
</form>